name: EffectUtils
version: 1.0.0
main: nguyen.quoc.nam.EffectUtils
api-version: '1.21'
commands:
  vanish:
    description: Toggle, enable, or disable vanish state.
    usage: /vanish <enable/disable> <player>
    permission: effectutils.vanish
    permission-message: You do not have permission to use this command!
  forget:
    description: Hides player nameplate, removes them from the tab list, and prevents autocomplete.
    usage: /forget <enable/disable> <player>
    permission: effectutils.forget
    permission-message: You do not have permission to use this command!
permissions:
  effectutils.vanish:
    description: Allows players to vanish.
    default: op
  effectutils.forget:
    description: Allows players to use /forget.
    default: op
